server:
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  mustache:
    servlet:
      expose-session-attributes: true


  servlet:
    multipart:
      max-file-size: 50MB
      maxRequestSize: 50MB